### ISSUE TITLE
Proposal: use diff-match-patch to update buffer without reload

### ISSUE THREAD

**Issue by ucirello** [Dgame/atom-php-fmt#4]
https://code.google.com/p/google-diff-match-patch/source/browse/#svn%2Ftrunk%2Fjavascript

See https://github.com/dericofilho/sublime-phpfmt/blob/master/phpfmt.py#L1301-L1370

**Comment by Dgame** [comment]
I'll look at it tomorrow evening, after work. :)

**Comment by Dgame** [comment]
Are you able to implement it?

**Comment by ucirello** [comment]
Not really. I am not an Atom user.

**Comment by Dgame** [comment]
Ok, I'll try it next week.

**Comment by Dgame** [comment]
Why closed?

**Comment by ucirello** [comment]
Actually, I tried it without such feature and it works pretty fine. That's why I closed.
