### ISSUE TITLE
Do not work.

### ISSUE THREAD

**Issue by iugo** [Dgame/atom-php-fmt#7]
PHP 5.6.11 (cli)
fmt.phar 13.4.0

![2015-09-09 18 40 53](https://cloud.githubusercontent.com/assets/499364/9759814/6e81b1d0-5722-11e5-85b0-ef9b20fb1438.png)

![2015-09-09 18 41 02](https://cloud.githubusercontent.com/assets/499364/9759813/6e7f0868-5722-11e5-80a1-6c88560a141c.png)

**Comment by Dgame** [comment]
Take a look to the console. Did you see any output / errors?

**Comment by iugo** [comment]
@Dgame 
![2015-09-11 10 15 52](https://cloud.githubusercontent.com/assets/499364/9805651/32c7175a-586e-11e5-841e-df7f464bc354.png)

**Comment by curtisblackwell** [comment]
I seem to be having the same issue. The errors I'm getting are slightly different, though I suspect that's because I'm on a newer version.

```
Up-to-date!                                                                           php-fmt.coffee:147
  stderr                @  php-fmt.coffee:147
  (anonymous function)  @  /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:85
  emitOne               @  events.js:77
  emit                  @  events.js:169
  readableAddChunk      @  _stream_readable.js:146
  Readable.push         @  _stream_readable.js:110
  onread                @  net.js:523

php exited with code: 0                                                               php-fmt.coffee:148
```

<img width="641" alt="screen shot 2015-11-17 at 10 20 45 am" src="https://cloud.githubusercontent.com/assets/468029/11199884/ea41ec36-8d14-11e5-8b08-cbd10a614c2f.png">

```
[10:08:17][🐐 ][~/sites/v2](master)> php -v
PHP 5.6.15 (cli) (built: Oct 31 2015 07:39:39) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

Any idea what might be wrong with my setup?

**Comment by curtisblackwell** [comment]
I found that disabling self-update seems to work, but I still get some errors.

![screen shot 2015-11-17 at 10 29 24 am](https://cloud.githubusercontent.com/assets/468029/11200072/1d1e7b96-8d16-11e5-9b9e-a5f193b47181.png)

Disabling PSR Naming takes care of one of them…

**Comment by Dgame** [comment]
I no longer use atom, therefore I do not work very much on this repo. But I will see if I find a solution at the weekend.

**Comment by daPhantom** [comment]
I fixed this by using the fmt.php file composer also installed instead of the phar file. Don't know why...

**Comment by Dgame** [comment]
Hm, me neither, but I'm glad that it works. :smile:
